import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  NEXT_PUBLIC_APP_NAME: z.string().min(1),
  NEXT_PUBLIC_APP_URL: z.string().url(),
  DATABASE_URL: z.string().min(1),
  NEXTAUTH_URL: z.string().url().optional(),
  NEXTAUTH_SECRET: z.string().min(1),
  OPENAI_API_KEY: z.string().optional(),
  ANTHROPIC_API_KEY: z.string().optional(),
  GEMINI_API_KEY: z.string().optional(),
  GROQ_API_KEY: z.string().optional(),
  MISTRAL_API_KEY: z.string().optional(),
  COHERE_API_KEY: z.string().optional(),
  PERPLEXITY_API_KEY: z.string().optional(),
  XAI_API_KEY: z.string().optional(),
  DEEPSEEK_API_KEY: z.string().optional(),
  TOGETHER_API_KEY: z.string().optional(),
  OPENROUTER_API_KEY: z.string().optional(),
  DEFAULT_AI_PROVIDER: z.enum(["openai", "anthropic", "gemini"]).default("gemini"),
  DEFAULT_AI_MODEL: z.string().min(1).default("gemini-3.1-pro-preview"),
  BROWSER_HEADLESS: z.string().optional(),
  BROWSER_ACTION_TIMEOUT_MS: z.string().optional(),
  BROWSER_ACTION_RETRY_COUNT: z.string().optional(),
  BROWSER_MAX_ACTIONS_PER_SESSION: z.string().optional(),
  BROWSER_ALLOWED_DOMAINS: z.string().optional(),
  BROWSER_CONFIRMATION_ACTIONS: z.string().optional(),
  BROWSER_SCREENSHOT_DIR: z.string().optional(),
  REDIS_URL: z.string().optional(),
  LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
  VERTEX_AI_PROJECT: z.string().optional(),
  VERTEX_AI_LOCATION: z.string().optional(),
  GOOGLE_APPLICATION_CREDENTIALS: z.string().optional(),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  GROQ_API_KEY: process.env.GROQ_API_KEY,
  MISTRAL_API_KEY: process.env.MISTRAL_API_KEY,
  COHERE_API_KEY: process.env.COHERE_API_KEY,
  PERPLEXITY_API_KEY: process.env.PERPLEXITY_API_KEY,
  XAI_API_KEY: process.env.XAI_API_KEY,
  DEEPSEEK_API_KEY: process.env.DEEPSEEK_API_KEY,
  TOGETHER_API_KEY: process.env.TOGETHER_API_KEY,
  OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
  DEFAULT_AI_PROVIDER: process.env.DEFAULT_AI_PROVIDER,
  DEFAULT_AI_MODEL: process.env.DEFAULT_AI_MODEL,
  BROWSER_HEADLESS: process.env.BROWSER_HEADLESS,
  BROWSER_ACTION_TIMEOUT_MS: process.env.BROWSER_ACTION_TIMEOUT_MS,
  BROWSER_ACTION_RETRY_COUNT: process.env.BROWSER_ACTION_RETRY_COUNT,
  BROWSER_MAX_ACTIONS_PER_SESSION: process.env.BROWSER_MAX_ACTIONS_PER_SESSION,
  BROWSER_ALLOWED_DOMAINS: process.env.BROWSER_ALLOWED_DOMAINS,
  BROWSER_CONFIRMATION_ACTIONS: process.env.BROWSER_CONFIRMATION_ACTIONS,
  BROWSER_SCREENSHOT_DIR: process.env.BROWSER_SCREENSHOT_DIR,
  REDIS_URL: process.env.REDIS_URL,
  LOG_LEVEL: process.env.LOG_LEVEL,
  VERTEX_AI_PROJECT: process.env.VERTEX_AI_PROJECT,
  VERTEX_AI_LOCATION: process.env.VERTEX_AI_LOCATION,
  GOOGLE_APPLICATION_CREDENTIALS: process.env.GOOGLE_APPLICATION_CREDENTIALS,
});
